"""index executions by status and created_at

Revision ID: 3c6b265f1ddb
Revises: ec6c519d31cf
Create Date: 2026-10-01 06:49:17.609567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6b265f1ddb'
down_revision: Union[str, Sequence[str], None] = 'ec6c519d31cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_executions_status_created_at', 'executions', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_status_created_at', table_name='executions')
    # ### end Alembic commands ###
