"""store timestamps with time zone

Revision ID: ec6c519d31cf
Revises: b6abc82bb645
Create Date: 2026-09-30 22:50:34.928965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec6c519d31cf'
down_revision: Union[str, Sequence[str], None] = 'b6abc82bb645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("executions", "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column("executions", "started_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="started_at AT TIME ZONE 'UTC'")
    op.alter_column("executions", "finished_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="finished_at AT TIME ZONE 'UTC'")
        # ### end Alembic commands ###


def downgrade() -> None:
    """Go back to naive timestamps, keeping the values in UTC."""
    op.alter_column(
        "executions", "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "executions", "started_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        postgresql_using="started_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "executions", "finished_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        postgresql_using="finished_at AT TIME ZONE 'UTC'",
    )